#!/usr/bin/env python3

import sys
from spot import *

if len(sys.argv) == 1:
    print(
        '''
        For help, use the command: spot help
        ''')
    sys.exit()

# spot help
if sys.argv[1] == 'help':
    spot_help()

# spot play ...
elif sys.argv[1] == 'play':
    play(sys.argv[2:])

# spot curr
elif sys.argv[1] == 'curr':
    curr()

# spot pause
elif sys.argv[1] == 'pause':
    pause()

# spot save
elif sys.argv[1] == 'save':
    save()

# spot n
elif sys.argv[1] == 'n':
    spot_next()

# spot p
elif sys.argv[1] == 'p':
    spot_prev()

# spot r
elif sys.argv[1] == 'r':
    repeat()

# spot rc
elif sys.argv[1] == 'rc':
    repeat(context=True)

# spot s
elif sys.argv[1] == 's':
    shuffle()
