#!/usr/bin/env python3

import sys
from spot import *

if len(sys.argv) == 1:
    print(
        '''
        For help, use the command: spot help
        ''')
    sys.exit()

# spot help
if sys.argv[1] == 'help':
    spot_help()

# spot play ...
elif sys.argv[1] == 'play':
    play(sys.argv[2:])

# spot pause
elif sys.argv[1] == 'pause':
    pause()

# spot n
elif sys.argv[1] == 'n':
    spot_next()

# spot p
elif sys.argv[1] == 'p':
    spot_prev()
